[package]
name = "music_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biquad = "0.4.2"
ciborium = "0.2.1"
colored = "2.0.0"
cpal = "0.15.0"
ctrlc = "3.2.5"
dasp_sample = "0.11.0"
futures = "0.3.28"
lazy_static = "1.4.0"
log = { version = "0.4.17", features = [
    "max_level_trace",
    "release_max_level_debug",
    "serde",
] }
realfft = "3.2.0"
reqwest = "0.11.16"
rustfft = "6.1.0"
serde = "1.0.162"
tokio = {version = "1.27.0", features = ["full"]}
webrtc-dtls = "0.7.2"
