[package]
name = "music_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biquad = "0.4.2"
bytes = "1.5.0"
ciborium = "0.2.1"
colored = "2.0.4"
cpal = "0.15.2"
ctrlc = "3.4.1"
dasp_sample = "0.11.0"
gethostname = "0.4.3"
log = { version = "0.4.20", features = [
    "max_level_trace",
    "release_max_level_debug",
    "serde",
] }
plotters = "0.3.5"
realfft = "3.3.0"
reqwest = {version = "0.11.23", features = ["json"]}
rodio = "0.17.1"
rustfft = "6.1.0"
serde = "1.0.193"
tokio = {version = "1.35.1", features = ["full"]}
toml = "0.8.10"
webrtc-dtls = "0.8.0"
