name: auto-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ready_for_review]
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Format
      run: cargo fmt
    - name: Check for modified files
      id: git-check
      run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'MarcelLieb'
        git config --global user.email '48131650+MarcelLieb@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Automated changes"
        git push
